### ISSUE TITLE
About MongoDB

### ISSUE THREAD

**Issue by KanghoonYoon** [LoadingByte/are-gnn-defenses-robust#2]
Thank you for sharing your code. I think this work is very nice for the research communities that are interested in the adversarial robustness of graph.

However, I cannot easily reproduce the code due to the implementation based on the MongoDB. Do you have any plan for adding the setting for Mongo DB. Otherwise, can you add a link for setting to use pymongo in your readme.md of the repository?

I cannot resolve the following errors.

pymongo.errors.ServerSelectionTimeoutError: 143.xxx.xx.xx:xxxxx: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64a3adb83c180daa30bebe56, topology_type: Unknown, servers: [<ServerDescription ('143.xxx.xx.xx', xxxxx) server_type: Unknown, rtt: None, error=AutoReconnect('143.xxx.xx.xx:xxxxx: [Errno 111] Connection refused')>]>

**Comment by toggled** [comment]
Hi, Any updates on this issue?

**Comment by LoadingByte** [comment]
Sorry for the long delay!

You're right that Mongo DB can be a pain. However, this codebase also works without it, as is illustrated in the [demo.ipynb](https://github.com/LoadingByte/are-gnn-defenses-robust/blob/master/notebooks/demo.ipynb) notebook. So it's likely you won't need Mongo DB for most use cases.

The only use case that requires Mongo DB is running the large-scale attack experiment (whose results we've summarized in the paper). To tell the codebase how to connect to the DB, create a file with the following content at
`~/.config/seml/mongodb.config`:

```
username: XXX
password: YYY
port: 12345
database: ZZZ
host: example.com
```

`host` can of course also be set to `localhost` if you're running Mongo DB locally.

I hope this helps! If not, feel free to reach out again! :)
